### ISSUE TITLE
Ability to see DQR Report link with  add_dqr_to_qc (or an additional class to the QC module)

### ISSUE THREAD

**Issue by caghili** [ARM-DOE/ACT#547]
Something along these lines, having the ability to get the DQR report for a datasteam of interest via python  would cut down on some time.  like somehow spit out a link after add_dqr_to_qc. Since sometimes datastreams have no dqr reports.

**Comment by kenkehoe** [comment]
Would make sense to create a new function/method to get this information and print out. Maybe create a function to pass in datastreams and date range. Also a method to loop through datastreams and variables in dataset time range.

**Comment by AdamTheisen** [comment]
@kenkehoe have you had a chance to look into this or should we see if someone else can take it on?

**Comment by kenkehoe** [comment]
I have not looked into this. I have been talking with the ADC about updating the DQR API. Maybe we can integrate some of this. Otherwise if all we need is a view of the DQR we could use the DQR API to get a list of DQR IDs and then create links to the ADC DQR view using this URL: https://www.archive.arm.gov/ArchiveServices/DQRService?dqrid=D700101.1
