### ISSUE TITLE
Make SkewT Display More Flexible with Matplotlib

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/ACT#607]
While taking a look at #606 , I noticed that there is not currently a way to feed in a user-defined figure or axes to the SkewT Display. This would be an important feature to add, enabling users to customize their plots more, and interact with other displays.

**Comment by AdamTheisen** [comment]
@mgrover1 I might need to spend some more time on this, but I'm not sure if it's possible with how MetPy has the SkewT function set up at the moment.  I.e. I would assume the following would have worked

```
import act
import matplotlib.pyplot as plt
import glob

files = glob.glob('./sgpsondewnpnC1.b1/*')[0]
ds = act.io.read_netcdf(files)
fig, axs = plt.subplot_mosaic([['a', 'a', 'b'], ['a', 'a', 'c'], ['a', 'a', 'c']], layout='constrained')
display = act.plotting.SkewTDisplay(ds)
display.assign_to_figure_axis(fig, axs['a'])
display.plot_from_u_and_v('u_wind', 'v_wind', 'pres', 'tdry', 'dp')
plt.show()
```

But i just get a blank plot because it looks like SkewT creates it's own axes.  It looks like we could update to use gridspec but that doesn't get around the need to supply a fig/axes to plot on.

Any thoughts here?

**Comment by mgrover1** [comment]
@AdamTheisen the SkewT object has an option to pass in a figure
https://github.com/Unidata/MetPy/blob/main/src/metpy/plots/skewt.py#L264

It also has an `ax` object we can access
https://github.com/Unidata/MetPy/blob/main/src/metpy/plots/skewt.py#L313

**Comment by AdamTheisen** [comment]
@mgrover1 just needed a little more time. Now we should be able to use with subplot_mosaic's as well.

**Comment by mgrover1** [comment]
@AdamTheisen great! Neat to see.
