### ISSUE TITLE
Issue reading netcdf files using base + offset

### ISSUE THREAD

**Issue by sophiaanr** [ARM-DOE/ACT#611]
We are making quicklook images with Netcdf files generated from Dave Turners latest TROPoe Docker image. He doesn't have his time conforming to CF conventions yet and using the data in Xarray is failing. Files are being loaded using decode_times=False, however the base_time + time_offset is calculated incorrectly due to missing parentheses. Dave is aware of this problem with his data and said he will make the correction in a future release.

**Comment by AdamTheisen** [comment]
Thanks for letting us know @sophiaanr !  Do you have a sample file we could look at?

**Comment by sophiaanr** [comment]
Sure - looks like GitHub won't allow me to upload a netcdf file, what's the best way to send it to you?

**Comment by AdamTheisen** [comment]
@sophiaanr please send me an email or if you are able to upload to box/google drive and note that link here.  I'm assuming you're working with the AERI team at UW right?  Denny will have my email.

**Comment by AdamTheisen** [comment]
@sophiaanr I got a file from Denny and did some testing.  Since the files are not following ARM standards I would recommend not using the ARM-specific netcdf reader in ACT but instead just using xarray to read in the data which appears to work fine.  I used the following code to read it in using xarray and then used ACT to plot it.  Let me know if this works for you or not.

```
import act
import xarray as xr
import matplotlib.pyplot as plt

file = './tropoe20msnaoss.20230127.002010.nc'
obj = xr.open_mfdataset(file)
display = act.plotting.TimeSeriesDisplay(obj)
display.plot('temperature')
plt.show()
```

**Comment by sophiaanr** [comment]
Sure, this works but the times appear incorrect in the plot. I'm expecting times to go from approx 2023-01-27T00:20:10 to 2023-01-27T13:20:10 or so. 

I'm loading the files like this, which compiles with no errors, but the time + offset calculation is wrong. The bug I'm referring to is in line 221 of armfiles.py, which attempts to convert the time offsets before adding base time. 
```python
import act
file = './tropoe20msnaoss.20230127.002010.nc'
aerioe_ds = act.io.armfiles.read_netcdf(file, decode_times=False)
```

I've gotten it to work by doing this: 
```python
time = ((base_time + time_offset) * 1000000.0).astype('datetime64[us]')
```

**Comment by AdamTheisen** [comment]
@sophiaanr apologies, that was my oversight!  I put the change in on my version and ran the tests and they all passed so I think we can go ahead with that update.  Would you be interested in submitting a Pull Request with this change?  I can always do it as well, but also very happy to have a new contributor!

Also pinging @kenkehoe since he's done a lot of work with base_time and timeoffset in these codes and want to make sure I'm not missing anything.

Thanks!

**Comment by kenkehoe** [comment]
@sophiaanr sorry after looking into this more I do not believe there is any possibility of a units issue by using base_time + time_offset. Those are always going to be in seconds since 1970-01-01 00:00:00 UTC. In fact ACT uses those two variables as a backup to the the time variable in cases like this where the units attribute is incorrectly formatted. Looks like I could add some more error handling to fix this issue automatically. Thanks for pointing this out.

**Comment by sophiaanr** [comment]
Awesome, thanks for the help! Let me know if you need anymore information from me. I can submit a pull request for that one change or I can leave it to you if you're thinking of adding some extra error handling.

**Comment by kenkehoe** [comment]
This will need some extra logic to handle the edge cases. Let's leave this as an issue for now and I'll work on it soon.

**Comment by AdamTheisen** [comment]
Thanks for the work here @kenkehoe!  @sophiaanr with this latest update the following should work to read in the data.  I'm going to close this out but please let us know if you are still having issues.

```
obj = act.io.armfiles.read_netcdf(file, decode_times=False, use_base_time=True)
```
