### ISSUE TITLE
Filtering of data in plots (like a Py-ART gatefilter)

### ISSUE THREAD

**Issue by rcjackson** [ARM-DOE/ACT#72]
Like what we have in the Py-ART GateFilter, we should have a way to filter out values when viewing/processing data. I see an ACT "gatefilter" in the future, but perhaps we can call it a DataFilter object.

**Comment by kenkehoe** [comment]
I created the qcfilter.get_masked_data() method [located in qc.qcfilter file] to return filtered data based on QC status. Are you suggesting a filter to change the data in the object directly?

**Comment by kenkehoe** [comment]
I think we should spend some time working on this. I suggest using the qcfilter.get_masked_data() to get a clean numpy array and then put that back into the object. This would then make plots with all the filtered data removed. That would be easier than not changing the data in the object and needing to call the method for every processing task. Since xarray has so many option for processing we should use them. The other question is can we convert the dask array containing number arrays to numpy masked arrays? Will that work with the xarray processing options?

**Comment by kenkehoe** [comment]
This has been resolved with PR #245 .
